### PR TITLE
Add a configurable countdown option

### PR DESCRIPTION
**Pull request by ResistanceTo**

### CODE REVIEW

**Comment by ResistanceTo** [comment]
Add a configurable countdown option that allows a few seconds for video recording preparation

**Review by Mnpn — COMMENTED** [review]
Hi, thanks for the PR! This looks pretty good - and thanks for translating!
- I think it would probably be best if the countdown value was to be limited to e.g. 0-99, because you can currently enter negative values and also cause arithmetic overflows (crashes)
- (Bonus idea that you don't have to add for me to merge the PR) It would be nice if it were possible to cancel a countdown, e.g. by clicking the recording indicator (or pressing the set keybind again)

**Comment by ResistanceTo** [comment]
The first issue regarding the value range (0-99) has been fixed. As for the second suggestion, I personally don't think it's a good idea. We already have a 'start recording' shortcut key, and adding a 'skip countdown to start recording' feature seems to defeat the purpose of having a countdown. Our default countdown value is set to 0.

**Comment by Mnpn** [comment]
Ah, I think you misunderstood, I meant that it should be possible to cancel the recording itself during a countdown; say you have a 10 second countdown, and started a recording you didn't mean to, there is no way to stop and you have to wait for it to finish counting down :P But this looks good so I'll go ahead and merge it -- thanks again for the PR!

**Pull request merged**
