### PR TITLE
Improved user interface, and rewritten some AppKit codes into SwiftUI

### PR DESCRIPTION
**Pull request by lihaoyun6**
1. Added zh_Hans localization (include warning text in stdout, but not enabled by default)

3. Added icons for each application to the Windows list
4. Added a timer view for the status bar item (only when recording)
5. Deprecate the AppKit main entry in `main.swift` and replace it with native SwiftUI method
6. Create preferences window using SwiftUI instead of AppKit

### CODE REVIEW

**Review by Mnpn — COMMENTED** [review]
This is great, thank you for the PR! This looks really good, and thanks for taking the time to translate! I have a few comments though:
- I think you forgot to commit the project file (perhaps you changed your development team and wanted to exclude that, but the new files are not listed in Xcode and it thus won't build without removing `main.swift` and adding MenuBar).
- When there are no windows and you open and close the menu repeatedly, the "No windows" text appears at the top too (I think this is because of the change in #15). I also noticed that some windows lose parts of their text when the UI updates this way. If I recall correctly, updating the menu when it's about to open or close generally causes strange behaviour.. The better way to address the issue mentioned might be to do something similar to `refreshWindows()` instead? I can have a look at this later if you'd like
- The preferences window is really wide when opening with SwiftUI, is this intentional?

**Comment by lihaoyun6** [comment]
Thanks for the reminder, I'm working on more improvements, including:
- merging window list items by application
- more video encoding options
- get monitor local name
- add "screen the mouse is currently on" indicator
- user notifications
...

As for the issues you found, I will fix them as soon as possible and update this pull request (with all the new features mentioned above)  

image
image
<br>image

**Comment by lihaoyun6** [comment]
> I think you forgot to commit the project file..  

The missing files have been uploaded in the latest commit

> When there are no windows and you open and close the menu repeatedly, the "No windows" text appears at the top too...  
  
Since I merged the window list by application, I discarded the `else{}` part of the `updateMenu()` function.  
Because I thought that instead of using multiple nested loops to update the menu, it would be better to rebuild the menu before each expansion than to use multiple nested loops

> The preferences window is really wide when opening with SwiftUI...  

I just forgot to add the `.fixedSize()` decorator to the `Preferences()` view, my bad =D

**Comment by lihaoyun6** [comment]
😆And I want to know why this app is called "Azayaka"? Does it have any special meaning?

**Comment by lihaoyun6** [comment]
https://github.com/Mnpn/Azayaka/assets/16348097/1c6ccbb7-bacd-40c3-be3e-def75bf48e9a

I added the ability to "capture specific applications" to Azayaka! 😆😆😆

**Review by Mnpn — APPROVED** [review]
Awesome, looks good to me! Quick question regarding the new menu icon, have you made it yourself or is it licensed in a way that lets it be used here? Otherwise, perhaps try `Image(systemName: "camera.on.rectangle.fill")` and see if you think that one is better than the `record.circle`

**Comment by Mnpn** [comment]
> 😆And I want to know why this app is called "Azayaka"? Does it have any special meaning?

Haha it is just a [random Japanese adjective](https://jisho.org/word/%E9%AE%AE%E3%82%84%E3%81%8B), probably something I had in my [SRS review](https://en.wikipedia.org/wiki/Spaced_repetition) pile at the time :)

**Comment by lihaoyun6** [comment]
> Awesome, looks good to me! Quick question regarding the new menu icon, have you made it yourself or is it licensed in a way that lets it be used here? Otherwise, perhaps try `Image(systemName: "camera.on.rectangle.fill")` and see if you think that one is better than the `record.circle`

Yes, the new menu bar icon was drawn by myself. I think this project should have its own "iconic feature". It's time to design a dedicated menu bar icon for it.

**Comment by Mnpn** [comment]
Thanks again for the PR!

**Pull request merged**
